yaml: 1 # Explicitamente define la versión del Blueprint YAML

services:
  # Servicio Backend (API de FastAPI)
  - type: web # Tipo de servicio: Web Service (accesible desde internet)
    name: cloudscan-backend # Nombre del servicio en Render
    env: python # Entorno de ejecución
    rootDir: backend # Directorio raíz del código para este servicio
    buildCommand: "" # El Dockerfile se encarga de la construcción
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000 # Comando para iniciar la aplicación
    healthCheckPath: / # Ruta para la verificación de salud
    ports:
      - 8000 # Puerto que expone el servicio

  # Servicio ClamAV (Antivirus)
  - type: worker # Tipo de servicio: Worker (corre en segundo plano, accesible internamente)
    name: cloudscan-clamav # Nombre del servicio en Render
    env: docker # Entorno de ejecución: Docker (construye desde Dockerfile)
    rootDir: clamav # Directorio raíz del Dockerfile para ClamAV
    buildCommand: "" # El Dockerfile se encarga de la construcción
    startCommand: clamd -c /etc/clamav/clamd.conf # Comando para iniciar el demonio ClamAV
    ports:
      - 3310 # Puerto que expone ClamAV

  # Servicio Frontend (Nginx sirviendo HTML/JS/CSS)
  - type: web # Tipo de servicio: Web Service (accesible desde internet)
    name: cloudscan-frontend # Nombre del servicio en Render
    env: docker # Entorno de ejecución: Docker (construye desde Dockerfile)
    rootDir: frontend # Directorio raíz donde está el Dockerfile para el frontend
    buildCommand: "" # El Dockerfile se encarga de la construcción
    startCommand: nginx -g 'daemon off;' # Comando para iniciar Nginx en primer plano
    ports:
      - 80 # Puerto que expone el frontend
    healthCheckPath: / # Ruta para la verificación de salud
