# fly.toml para el servicio clamav
app = "clamav-black-resonance-1066" # Asegúrate de que este sea el nombre exacto de tu aplicación ClamAV en Fly.io
primary_region = "iad" # Usa la región donde desplegaste tu aplicación ClamAV

[build]
  dockerfile = "Dockerfile"

# Configuración para el volumen persistente.
# Asegúrate de haber creado este volumen con:
# flyctl volumes create clamav_data --region iad --size 10
[mounts]
  source="clamav_data" # Nombre del volumen persistente que creaste
  destination="/var/lib/clamav" # Ruta dentro del contenedor donde ClamAV guarda las firmas

[http_service]
  internal_port = 3310 # Puerto interno que ClamAV expone
  force_https = false # No necesitamos HTTPS para un servicio interno
  auto_stop_machines = true # Permite que la máquina se detenga si no hay tráfico
  auto_start_machines = true # Permite que la máquina se inicie con el tráfico
  min_machines_running = 0 # Permite escalar a cero si no hay uso
  processes = ["app"]

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
