# fly.toml app configuration file generated for clamav-black-resonance-1066 on 2025-07-20T15:37:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clamav-black-resonance-1066'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"
[http_service]
  internal_port = 3310
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
